Fixed templates.

diff --git a/graalvm-jdk-20/linux-x64 b/graalvm-jdk-20/linux-x64
--- a/graalvm-jdk-20/linux-x64
+++ b/graalvm-jdk-20/linux-x64
@@ -35,16 +35,22 @@ curl -s "${jdkUrl}" | tar -xzC "${jdkDestDir}"
 if test ! -f "${envScript}"; then
     touch "${envScript}"
 fi
-grepResult=$(grep -qF "${javaHomeLine}" "${envScript}" ; echo $?)
-if test "${grepResult}" -ge 2; then
-    echo "${cc_error}Error adding JAVA_HOME.${c_reset}"
-    exit 1
-fi
-if test "${grepResult}" != 0; then
+readonly grepResult=$(grep -qF "${javaHomeLine}" "${envScript}" ; echo $?)
+if test "${grepResult}" -eq 0; then
     # Not found. Let's add it.
     echo "${javaHomeLine}" >> "${envScript}"
     echo >> "${envScript}"
     echo "${cc_message}JAVA_HOME added to '.profile'.${c_reset}"
+fi
+if test "${grepResult}" -eq 1; then
+    # There is one. Replace it.
+    sed -i "'s|^export JAVA_HOME=.*|${javaHomeLine}|'" "${envScript}"
+    echo "${cc_message}JAVA_HOME replaced in '.profile'.${c_reset}"
+fi
+if test "${grepResult}" -ge 2; then
+    # Nah! Something is wrong.
+    echo "${cc_error}Error adding JAVA_HOME.${c_reset}"
+    exit 1
 fi
 
 echo "${cc_success}Make sure to close and reopen this terminal.${c_reset}"
